title: Lanky Local Sharpening Services
logo: /assets/img/logo.png
description: Sharpening anything gone dull for Sherburne County and the surrounding Metro.
show_downloads: false
google_analytics:
theme: jekyll-theme-minimal
